### ISSUE TITLE
Add oop features

### ISSUE THREAD

**Issue by timo-cmd2** [space-lang/spacedocs#2]
För nici oop fealings, Adde please das:

- classes
- Polymorphic classes 
- Objects
- Methods
- Extensions
- Inheritance
- Interfaces
- optional external concurrency mit actor classes

**Comment by krissemicolon** [comment]
yes, i will add oop support soon
thx for the suggestion

**Comment by lianstuder** [comment]
I would not add all of the features suggested above. It bloats the language. Features like interfaces, simple classes and methods would suffice. Inheritance should be illegal anyways (lolmao).

**Comment by timo-cmd2** [comment]
Just wanna keep functional semantics in front and center or wha? xD

**Comment by lianstuder** [comment]
Yes
Lodash type beat 











jk

**Comment by timo-cmd2** [comment]
Bruh shit lodash
